import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const routers: string[] = ['/question1/1/Q1', '/question1/1/Q2', '/question1/2', '/question1/3', '/question1/4', '/question1/5', '/question1/6']

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <div className="nav">
      {routers.map((router) => (
        <Link href={router}>
          <div>
            <button>
              {router}
            </button>
          </div>
        </Link>
      ))}
    </div>
    {children}
    </body>
    </html>
  )
}
