import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { routers } from '@/data/routers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <div className="nav">
      {routers.map((router) => (
        <Link href={router}>
          <div>
            <button>
              {router.split('/').slice(1).join('. ')+'.'}
            </button>
          </div>
        </Link>
      ))}
    </div>
    {children}
    </body>
    </html>
  )
}
